const images = {
  alrawiikon: "/images/aalrawilogodark2026.png",
  alrawiLogo: "/images/alrawilogodark2026.png",
  arrowAirplane: "/images/arrow-airplane-ilist.png",
  arrowIlist: "/images/arrow-ilist.png",
  dahsedIlist: "/images/dahsed-ilist.png",
  design01: "/images/design-01.png",
  design02: "/images/design-02.png",
  footerBg: "/images/footer-bg.png",
  footerCom: "/images/footer-com.png",
  footerYasir: "/images/footer-yasir.png",
  heroBg: "/images/hero-bg.png",
  heroYasir: "/images/hero-yasir.png",
  huaweiLogo: "/images/huaweiLogo.png",
  icoSoc01: "/images/ico_soc-01.svg",
  icoSoc02: "/images/ico_soc-02.svg",
  icoSoc03: "/images/ico_soc-03.svg",
  icoSoc04: "/images/ico_soc-04.svg",
  icoSoc05: "/images/ico_soc-05.svg",
  logo: "/images/alrawilogolight2026.png",
  numb01: "/images/numb-01.png",
  numb02: "/images/numb-02.png",
  numb03: "/images/numb-03.png",
  numb04: "/images/numb-04.png",
  numb05: "/images/numb-05.png",
  numb06: "/images/numb-06.png",
  paperAirplane: "/images/paper-airplane.png",
  paypalLogo: "/images/paypalLogo.png",
  seo01: "/images/seo-01.png",
  seo02: "/images/seo-02.png",
  person01: "/images/person-01.png",
  person02: "/images/person-02.png",
  person03: "/images/person-03.png",
  programming01: "/images/programming-01.png",
  programming02: "/images/programming-02.png",
  syllabusWomen: "/images/syllabus_women.png",
  transferWiseLogo: "/images/TransferWiseLogo.png",
  womenIlist: "/images/women_ilist.png",
  wooCommerceLogo: "/images/WooCommerceLogo.png",
};

export default images;